# Task - 6 

# 1. Arrays

In [1]:
import numpy

def arrays(arr):
    arr = numpy.array(arr, float)
    rev_arr = arr[::-1]
    return rev_arr

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 5 8 4 9 34
[34.  9.  4.  8.  5.  1.]


# 2. Shape and Reshape

In [1]:
import numpy as np
arr = np.array(list(map(int,input().split())))
print(np.reshape(arr,(3,3)))

1 2 5 3 7 9 6 4 9
[[1 2 5]
 [3 7 9]
 [6 4 9]]


# 3. Transpose and Flatten

In [3]:
import numpy as np
n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# 4.Concatenate

In [4]:
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# 5. Zeros and Ones

In [5]:
nums = tuple(map(int, input().split()))
print (np.zeros(nums, dtype = np.int))
print (np.ones(nums, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# 6. Eye and Identity

In [6]:
print(str(np.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# 7. Array Mathematics

In [7]:
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# 8. Floor, Ceil and Rint

In [8]:
np.set_printoptions(sign=' ')

a = np.array(input().split(),float)

print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# 9. Sum and Prod

In [11]:
N, M = map(int, input().split())
A = np.array([input().split() for _ in range(N)],int)
print(np.prod(np.sum(A, axis=0), axis=0))

2 2 
1 2
3 4 
24


# 10. Min and Max

In [12]:
n, m = list(map(int, (input().split())))
a = np.array([list(map(int,(input().split()))) for i in range(int(n))])
print(np.max(np.min(a, axis = 1), axis = None))

2 4
2 5
3 7
3


# 11. Mean, Var, and Std

In [13]:
N, M = map(int, input().strip().split())

my_array = np.array([ input().strip().split() for _ in range(N) ], int)

print(np.mean(my_array, axis = 1))
print(np.var(my_array, axis = 0))
print(round(np.std(my_array, axis = None),11))

2 2 
1 2 
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# 12. Dot and Cross

In [14]:
a=int(input())
arr1=np.array([list(map(int,input().split())) for _ in range(a)])
arr2=np.array([list(map(int,input().split())) for _ in range(a)])
print(np.dot(arr1,arr2))

2
1 2 
3 4
4 5
3 4
[[10 13]
 [24 31]]


# 13. Inner and Outer

In [15]:
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

2 3 
4 5
23
[[ 8 10]
 [12 15]]


# 14. Polynomials

In [17]:
a = list(map(float, input().split()))
print(np.polyval(a, float(input())))

1.1 2 3
0
3.0


# 15. Linear Algebra

In [18]:
n=int(input())
a=np.array([input().split() for _ in range(n)],float)
np.set_printoptions(legacy='1.13')
print(np.linalg.det(a))

2
1.1 1.1
1.1 1.1
0.0
